
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/proc.ipynb

from pathlib import Path

import pandas as pd
import sentencepiece as sp

import csv

def df_to_txt_file(df, output):
    with open(output/'text.txt', 'w') as f:
        f.write('\n'.join(list(merged_trn_df["query"]) + list(merged_trn_df["res"])))
    return output/'text.txt'

def gen_sp_model(df, output):
    fname = df_to_txt_file(df, output)
    sp.SentencePieceTrainer.train(f'--input={fname} --model_prefix={output}/model')

class SentencePiece:
    "SentencePiece wrapper."
    def __init__(self, mdl_path):
        self.mdl_path = mdl_path
        self.s = sp.SentencePieceProcessor()
        self.s.Load(str(mdl_path))

    def tokenize(self, inpt):
        return self.s.EncodeAsPieces(inpt)