
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/data_prep.ipynb

import json

import pandas as pd
from pathlib import Path

def jsonl_df(file_list, columns, compression=None):
    """Load a list of jsonl.gz files into a pandas DataFrame."""
    return pd.concat([pd.read_json(f,
                                   orient='records',
                                   compression=compression,
                                   lines=True)[columns]
                      for f in file_list], sort=False)